sudo: required
services:
  - docker



before_install:
  - docker build -t nadek/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true  nadek/react-test npm test  -- --coverage

after_success:
  - docker build -t nkabanova/multi-client ./client
  - docker build -t nkabanova/multi-nginx ./nginx
  - docker build -t nkabanova/multi-server ./server
  - docker build -t nkabanova/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push nkabanova/multi-client
  - docker push nkabanova/multi-nginx
  - docker push nkabanova/multi-server
  - docker push nkabanova/multi-worker

deploy: 
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-420175422320
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:$AWS_SECRET_KEY

