sudo: required
services:
  - docker


before_install:
  - docker build - t nadek/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true  nadek/react-test npm test  -- --coverage

after_success:
  - docker fuild -t nadek/multi-client ./client
  - docker build -t nadek/multi-nginx ./nginx
  - docker build -t nadek/multi-server ./server
  - docker build -t nadek/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push nadek/multi-client
  - docker push nadek/multi-nginx
  - docker push nadek/multi-server
  - docker push nadek/multi-worker

